# promtail-values.yaml - Configuración OPTIMIZADA con mejores prácticas
# QoS Guaranteed para componentes críticos, CPU sin límites para bursts

config:
  clients:
    - url: http://loki-gateway/loki/api/v1/push
      tenant_id: 1

  positions:
    filename: /tmp/positions.yaml

  target_config:
    sync_period: 20s  # Optimizado: ni muy frecuente ni muy lento

  scrape_configs:
    - job_name: kubernetes-pods
      kubernetes_sd_configs:
        - role: pod
      pipeline_stages:
        - cri: {}
      relabel_configs:
        - source_labels:
            - __meta_kubernetes_pod_controller_name
          regex: ([0-9a-z-.]+?)(-[0-9a-f]{8,10})?
          action: replace
          target_label: __tmp_controller_name
        - source_labels:
            - __meta_kubernetes_pod_label_app_kubernetes_io_name
            - __meta_kubernetes_pod_label_app
            - __tmp_controller_name
            - __meta_kubernetes_pod_name
          regex: ^;*([^;]+)(;.*)?$
          action: replace
          target_label: app
        - source_labels:
            - __meta_kubernetes_pod_label_app_kubernetes_io_instance
            - __meta_kubernetes_pod_label_instance
          regex: ^;*([^;]+)(;.*)?$
          action: replace
          target_label: instance
        - source_labels:
            - __meta_kubernetes_pod_label_app_kubernetes_io_component
            - __meta_kubernetes_pod_label_component
          regex: ^;*([^;]+)(;.*)?$
          action: replace
          target_label: component

resources:
  requests:
    cpu: 15m      # CPU solo request para permitir bursts
    memory: 64Mi  # Aumentado de 40Mi a 64Mi para evitar OOMKilled
  limits:
    memory: 64Mi  # Solo memory limit = request para QoS Guaranteed

# Configuración de tolerancias y afinidad mínima
tolerations: []
affinity: {}

# Configuración de monitoreo deshabilitada
serviceMonitor:
  enabled: false

# Configuración de seguridad mínima
podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

# Configuración de volúmenes mínima
extraVolumes: []
extraVolumeMounts: [] 