---
# Variables por defecto para el rol de sistema
# Estas variables pueden ser sobrescritas en group_vars o host_vars

# Configuraci칩n de timezone
system_timezone: Europe/Madrid

# Par치metros del kernel para Kubernetes
kernel_parameters:
  - { key: 'net.bridge.bridge-nf-call-iptables', value: '1' }
  - { key: 'net.bridge.bridge-nf-call-ip6tables', value: '1' }
  - { key: 'net.ipv4.ip_forward', value: '1' }
  - { key: 'vm.swappiness', value: '1' }

# M칩dulos del kernel requeridos
kernel_modules:
  - br_netfilter
  - overlay

# Configuraci칩n de WireGuard
wireguard_config_path: "/etc/wireguard"
wireguard_config_mode: "0700" 