# hcloud-cluster-config-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: hcloud-cluster-config
  namespace: kube-system
type: Opaque
stringData:
  config: |
    {
      "token": "",
      "nodeConfigs": {
        "k3s-cluster": {
          "serverType": "cx22",
          "location": "fsn1",
          "image": "ubuntu-24.04",
          "sshKey": "cluster-k3s-ssh",
          "cloudInit": "#cloud-config\npackages:\n- curl\nruncmd:\n- curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.28.5+k3s1 K3S_TOKEN=YOUR_K3S_TOKEN K3S_URL=https://YOUR_MASTER_IP:6443 sh -s - agent\n- systemctl enable k3s-agent\n- systemctl start k3s-agent"
        }
      }
    } 