---
# Rol 03-docker: Instalación y configuración de Docker

- name: Añadir clave GPG de Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Añadir repositorio de Docker
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Instalar Docker
  apt:
    name: "{{ docker_packages }}"
    state: present
    update_cache: yes

- name: Configurar Docker para usar systemd como cgroup driver
  copy:
    content: "{{ docker_daemon_config | to_nice_json }}"
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'
  notify: Restart Docker

- name: Habilitar y iniciar Docker
  service:
    name: docker
    enabled: yes
    state: started

- name: Añadir usuario administrador al grupo docker
  user:
    name: "{{ admin_user }}"
    groups: docker
    append: yes 